version: '3.8'

services:
  auth-aca:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env  # Esta línea asegura que se carga el archivo .env
    network_mode: host  # Mantener en modo host